__include__:
  - /root/autodl-tmp/surgical/third_party/D-FINE/configs/dfine/custom/dfine_hgnetv2_m_custom.yml

output_dir: /root/autodl-tmp/surgical/artifacts/experiments/dfine_m_800
num_classes: 1
remap_mscoco_category: False
sync_bn: False
eval_spatial_size: [800, 800]
epochs: 14
checkpoint_freq: 2
print_freq: 50
use_amp: True
use_ema: True

train_dataloader:
  dataset:
    img_folder: /root/autodl-tmp/surgical/artifacts/dataset
    ann_file: /root/autodl-tmp/surgical/artifacts/dataset/annotations_train.json
    transforms:
      ops:
        - {type: RandomPhotometricDistort, p: 0.5}
        - {type: RandomHorizontalFlip}
        - {type: Resize, size: [800, 800]}
        - {type: SanitizeBoundingBoxes, min_size: 1}
        - {type: ConvertPILImage, dtype: float32, scale: True}
        - {type: ConvertBoxes, fmt: cxcywh, normalize: True}
      policy:
        name: stop_epoch
        epoch: 100
        ops: [RandomPhotometricDistort]
  total_batch_size: 8
  num_workers: 4
  collate_fn:
    type: BatchImageCollateFunction
    base_size: 800
    base_size_repeat: 3
    stop_epoch: 100
    ema_restart_decay: 0.9999
  shuffle: True

val_dataloader:
  dataset:
    img_folder: /root/autodl-tmp/surgical/artifacts/dataset
    ann_file: /root/autodl-tmp/surgical/artifacts/dataset/annotations_val.json
    transforms:
      ops:
        - {type: Resize, size: [800, 800]}
        - {type: ConvertPILImage, dtype: float32, scale: True}
  total_batch_size: 8
  num_workers: 4
  shuffle: False

optimizer:
  type: AdamW
  params:
    - params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.000005
    - params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.000005
      weight_decay: 0.0
    - params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.0
  lr: 0.00005
  betas: [0.9, 0.999]
  weight_decay: 0.000125

lr_scheduler:
  type: MultiStepLR
  milestones: [10]
  gamma: 0.1

lr_warmup_scheduler:
  type: LinearWarmup
  warmup_duration: 250
